# Generated by Django 4.1.2 on 2022-11-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomedopet', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
                ('diareserva', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
    ]
