# Generated by Django 4.1.2 on 2022-11-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, verbose_name='Telefone para contato'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='turno',
            field=models.CharField(choices=[('manhã', 'Manhã'), ('tarde', 'Tarde')], max_length=10, verbose_name='Turno'),
        ),
    ]
